# Generated by Django 3.0.2 on 2020-01-15 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('homepage', models.CharField(default=' ', max_length=300)),
                ('description', models.TextField(default=' ')),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('description', models.TextField(default=' ')),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default=' ')),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('city', models.ManyToManyField(related_name='cities', to='nodasf.City')),
                ('county', models.ManyToManyField(related_name='counties', to='nodasf.County')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(default=' ', upload_to='media/stock')),
                ('homepage', models.CharField(default='', max_length=300)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Category')),
                ('issue', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Issue')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default=' ')),
                ('homepage', models.CharField(default=' ', max_length=300)),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.City')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.County')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SF_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('free', models.BooleanField(default=False)),
                ('cost', models.CharField(blank=True, default='', max_length=100)),
                ('homepage', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.City')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.County')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.Genre')),
                ('venue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nodasf.Venue')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('homepage', models.CharField(default=' ', max_length=300)),
                ('description', models.TextField(default=' ')),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Category')),
                ('issue', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Issue')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.Organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first', max_length=100)),
                ('last_name', models.CharField(default='last', max_length=100)),
                ('picture', models.ImageField(default=' ', upload_to='media/faces')),
                ('homepage', models.CharField(default='', max_length=300)),
                ('description', models.TextField()),
                ('candidate', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.County')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.District')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.Level')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.Party')),
                ('upcoming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.SF_Event')),
            ],
        ),
        migrations.CreateModel(
            name='Local_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=300)),
                ('headline', models.CharField(default='', max_length=150)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.City')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.County')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Issue')),
            ],
            options={
                'ordering': ('-posted',),
            },
        ),
        migrations.AddField(
            model_name='district',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Level'),
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.County'),
        ),
        migrations.CreateModel(
            name='Bureaucrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='last', max_length=100)),
                ('first_name', models.CharField(default='first', max_length=100)),
                ('picture', models.ImageField(default=' ', upload_to='media/faces')),
                ('description', models.TextField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.Organization')),
                ('program', models.ManyToManyField(blank=True, null=True, to='nodasf.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(default=' ', upload_to='media/stock')),
                ('homepage', models.CharField(default='', max_length=300)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Category')),
                ('issue', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Issue')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
