# Generated by Django 3.0.2 on 2020-01-08 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default=' ', max_length=150)),
                ('lead', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(default='', upload_to='media/stock')),
                ('credit', models.CharField(default='', max_length=200)),
                ('videoQ', models.BooleanField(default=False)),
                ('video', models.CharField(blank=True, default='', max_length=500)),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Report_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('posted', models.DateTimeField(auto_now=True)),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/temp')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Event')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Org')),
            ],
            options={
                'ordering': ('-posted',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Theme'),
        ),
    ]
