# Generated by Django 3.0.2 on 2020-01-08 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0002_auto_20200108_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='event',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Event'),
        ),
    ]
