# Generated by Django 3.0.2 on 2020-01-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0004_other_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name here', max_length=100)),
                ('image', models.ImageField(default='', upload_to='media/stock')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
