# Generated by Django 3.0.2 on 2020-01-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0007_event_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='relateds', to='nodanews.Event'),
        ),
    ]
