# Generated by Django 3.0.2 on 2020-03-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0012_auto_20200225_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='slug',
            field=models.SlugField(default='slug here', max_length=100),
        ),
    ]
