# Generated by Django 3.0.2 on 2020-03-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0013_sequence_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='slug',
            field=models.SlugField(default=' slug here', max_length=100),
        ),
    ]
