# Generated by Django 3.0.2 on 2020-05-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0014_element_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='report_link',
            name='array',
        ),
        migrations.DeleteModel(
            name='Array',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
    ]
