# Generated by Django 3.0.2 on 2020-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0016_auto_20200505_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='front_page',
            name='left_pic_1',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='left_pic_1_credit',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='left_pic_2',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='left_pic_2_credit',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='middle_pic_1',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='middle_pic_1_credit',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='middle_pic_2',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='middle_pic_2_credit',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='right_pic_1',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='right_pic_1_credit',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='right_pic_2',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='right_pic_2_credit',
        ),
        migrations.RemoveField(
            model_name='front_page',
            name='variation',
        ),
        migrations.AddField(
            model_name='event',
            name='displayQ',
            field=models.BooleanField(default=False),
        ),
    ]
