# Generated by Django 3.0.6 on 2020-05-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0019_auto_20200508_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='readyQ',
            field=models.BooleanField(default=False),
        ),
    ]
