# Generated by Django 3.0.6 on 2020-05-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0020_event_readyq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_link',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
